@Library('Shared')_

pipeline {
    agent {
        label 'shakthiAgent'
    }
    environment {
        // Application
        APP_NAME = 'sparkNote'
        APP_VERSION = "1.0.${BUILD_NUMBER}"

        // Docker Images
        DOCKER_USERNAME = 'shakthivelk24'

        FRONTEND_IMAGE = "${DOCKER_USERNAME}/sparknote-frontend"
        BACKEND_IMAGE = "${DOCKER_USERNAME}/sparknote-backend"

        IMAGE_TAG = "${BUILD_NUMBER}"

        // SonarQube
        SONAR_PROJECT_KEY = 'sparkNote'

        // // Reports
        TRIVY_REPORT_DIR = 'reports/trivy'
    }
    options {
        // Add timestamps to all log lines for debugging
        timestamps()

        // Color ANSI codes in console output
        ansiColor('xterm')

        // Timeout the entire pipeline after 60 minutes
        // Prevents hung builds from consuming resources indefinitely
        timeout(time: 60, unit: 'MINUTES')

        // Keep only last 10 builds to save disk space
        buildDiscarder(logRotator(numToKeepStr: '10'))

        // Prevent multiple builds of the same branch running simultaneously
        disableConcurrentBuilds()
    }
    stages {
        // ====================================================
        // STAGE 1: CHECK TOOLS
        // ====================================================
        stage('Check Tools') {
            steps {
                cleanWs()
                customLog('Checking required tools...')
                check()
            }
        }
        // ====================================================
        // STAGE 2: CHECKOUT SOURCE CODE
        // ====================================================
        stage('🔄 Checkout') {
            steps {
                customLog('Checking out source code')

                checkout scm

                sh '''
                echo "========== Last 5 Commits =========="
                git log --oneline -5

                echo "========== Git Status =========="
                git status
            '''
            }
        }
        // ====================================================
        // STAGE 3: INSTALL DEPENDENCIES
        // ====================================================
        stage('📦 Install Dependencies') {
            stage('Frontend Dependencies') {
                    steps {
                        customLog('Installing frontend dependencies...')
                        npmInstall('frontend')
                    }
            }
        }
        // ====================================================
        // STAGE 4: RUN TESTS
        // Execute unit and integration tests
        // ====================================================
        stage('🧪 Run Tests') {
            parallel {
                stage('Frontend Tests') {
                    steps {
                        npmTest(
                         'frontend',
                         'vitest',
                         'coverage',
                         'junit.xml'
                        )
                    }
                }
                stage('Backend Tests') {
                    steps {
                        dir('BlogApplication') {
                            if (isUnix()) {
                                sh 'mvn clean test'
                            } else {
                                bat 'mvn clean test'
                            }
                        }
                    }
                }
            }
        }
        // ====================================================
        // STAGE 5: STATIC CODE ANALYSIS
        // Run SonarQube analysis on the codebase
        // ====================================================
        stage('🔍 Static Code Analysis') {
            steps {
                customLog('Running SonarQube analysis...')
                sonarqubeScan(
                     scannerName: 'SonarScanner',
                     sonarServer: 'SonarQube',
                     projectKey: SONAR_PROJECT_KEY,
                     projectName: APP_NAME,
                     projectVersion: APP_VERSION,
                     sources:
                         'client/src,BlogApplication/src',

                     exclusions: '''
                         **/node_modules/**,
                         **/dist/**,
                         **/build/**,
                         **/coverage/**,
                         **/lcov-report/**,
                         **/target/**,
                         **/*.test.js,
                         **/*.test.jsx,
                         **/*.spec.js,
                         **/*.spec.jsx
                     '''.trim().replaceAll('\\s+', ''),

                     // React
                     jsCoverage:
                         'client/coverage/lcov.info',

                     // Spring Boot
                     javaBinaries:
                         'BlogApplication/target/classes',

                     javaCoverage:
        '                 BlogApplication/target/site/jacoco/jacoco.xml'
                )
            }
        }
        // ====================================================
        // STAGE 6: QUALITY GATE
        // Check if the SonarQube quality gate passed or failed
        // ====================================================
        stage('✅ Quality Gate') {
            steps {
                customLog('Checking SonarQube quality gate...')
                waitForQualityGate()
            }
        }
    }
}
