spring.config.import=optional:file:.env[.properties]

server.port=8083
spring.application.name=BlogApplication
spring.datasource.url=${SQL_DB_URL}
spring.datasource.username=${SQL_DB_USERNAME}
spring.datasource.password=${SQL_DB_PASSWORD}
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}
